Repository oracle/oci-flexvolume-driver, pull requests merged in 2018-04, with the labels that each got.

#82 Update to latest OEL OCI image
  test/integration/terraform/instance.tf
Labels: tests

#80 Remove link to internal repo from documentation
  README.md
Labels: documentation

#87 Fixes #86 - support custom configuration directory
  README.md
  pkg/oci/driver/driver.go
  pkg/oci/driver/driver_test.go
Labels: enhancement

#88 Document auth policies
  README.md
Labels: documentation

#90 Return error if no subnets defined in vcn
  pkg/oci/client/oci.go
Labels: bug, enhancement

#92 Support deploying driver binary via daemonset (#38)
  Makefile
  README.md
  ansible/README.md
  ansible/ansible.cfg
  ansible/hosts.example
  ansible/roles/oci-flexvolume-driver/defaults/main.yaml
  ansible/roles/oci-flexvolume-driver/tasks/main.yaml
  ansible/roles/oci-flexvolume-driver/templates/config.yaml.j2
  ansible/site.yaml
  ci-docker-images/oci-flexvolume-driver-system-test/Dockerfile
  deploy.sh
  manifests/oci-flexvolume-driver.yaml
  test/system/ansible.cfg
  test/system/playbook.yaml
  test/system/runner.py
  wercker.yml
Labels: enhancement
